steps:
  # Get short commit SHA
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "COMMIT_SHA=$(git rev-parse --short HEAD)" > /workspace/commit.env

  # Load the COMMIT_SHA from the env file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit.env
        echo "Using image tag: $COMMIT_SHA"

  # Build Docker image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit.env
        docker build -t asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:$COMMIT_SHA ./app

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit.env
        docker push asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:$COMMIT_SHA

  # Patch Kubernetes deployment with the image containing commit SHA
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Patch Deployment YAML'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit.env
        sed "s|IMAGE_PLACEHOLDER|asia-south1-docker.pkg.dev/affable-hydra-467019-a9/zendesk/zendesk-image:${COMMIT_SHA}|" kubernetes/app.yaml > kubernetes/deploy-final.yaml

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/deploy-final.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=zendesk-cluster'
      - 'PROJECT_ID=affable-hydra-467019-a9'

options:
  logging: CLOUD_LOGGING_ONLY

